### PR TITLE
fix uncaught exception in http client

### LINKED ISSUE #245: Unhandled Exception when querying text-generation http endpoint
## Describe the bug

Attempting to query the `text-generation` http endpoint results in an uncaught exception

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: 3.11.5
- Library version: `caikit-nlp@63a674f`, `caikit@d2b930d`

## Sample Code
Download flan-t5-small model and convert it to caikit format (requires `git-lfs`)

```bash
git clone https://huggingface.co/google/flan-t5-small

python -c 'import caikit_nlp; model_path="flan-t5-small"; model = caikit_nlp.text_generation.TextGeneration.bootstrap(model_path); model.save(f"{model_path}-caikit")'
```

Run `caikit.runtime`

```bash
env runtime_LIBRARY=caikit_nlp RUNTIME_LOCAL_MODELS_DIR=$PWD python -m caikit.runtime
```

query the running server:

```bash
curl --json '{
    "model_id": "flan-t5-small-caikit",
    "inputs": "At what temperature does liquid Nitrogen boil?"
}' localhost:8080/api/v1/task/text-generation 
```

## Expected behavior

Get a response such as:

```json
{
  "generated_text": "74 degrees F",
  "generated_tokens": 5,
  "finish_reason": "MAX_TOKENS",
  "producer_id": {
    "name": "Text Generation",
    "version": "0.1.0"
  },
  "input_token_count": 10,
  "seed": null
}
```
## Observed behavior

Response:
```json
{
  "details": "Unhandled exception: 'MAX_TOKENS'",
  "code": 500,
  "id": null
}
```
Server stack trace:

```console
[uvicorn.acce:INFO:139624425285440] 127.0.0.1:40660 - "POST /api/v1/task/text-generation HTTP/1.1" 422
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E> 'MAX_TOKENS'
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E> Traceback (most recent call last):
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>   File "caikit/caikit/runtime/http_server/http_server.py", line 441, in _handler
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>     return Response(content=result.to_json(), media_type="application/json")
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>                             ^^^^^^^^^^^^^^^^
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>   File "caikit/caikit/core/data_model/base.py", line 991, in to_json
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>     return json.dumps(self.to_dict(), **kwargs)
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>                       ^^^^^^^^^^^^^^
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>   File "caikit/caikit/core/data_model/base.py", line 950, in to_dict
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>     dict_value = self._field_to_dict_element(field)
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>   File "caikit/caikit/core/data_model/base.py", line 1039, in _field_to_dict_element
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>     enum_rev[attr.value] if isinstance(attr, Enum) else enum_rev[attr]
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E>                                                         ~~~~~~~~^^^^^^
[SERVR-HTTP  :ERRR:139624425285440] <RUN51881106E> KeyError: 'MAX_TOKENS'
[uvicorn.acce:INFO:139624425285440] 127.0.0.1:47378 - "POST /api/v1/task/text-generation HTTP/1.1" 500
```
## Additional context

### PR DESCRIPTION
**Pull request by dtrifiro**
fixes #245

### CODE REVIEW

**Comment by dtrifiro** [comment]
Note: merge after #210

**Comment by evaline-ju** [comment]
I see https://github.com/caikit/caikit-nlp/pull/261 was put up from @Ssukriti that addresses basically the same issue but adds a test - could we potentially combine the work from these two PRs?

**Comment by Ssukriti** [comment]
You want to just merge this and then I will rebase my PR to add the test and fix the function argument typing as well ?

**Comment by dtrifiro** [comment]
@evaline-ju @Ssukriti the test in #261 does not actually test this issue, it passes with or without this patch and actually replicates behaviour of existing tests, such as `test_run_model` (and others):

https://github.com/caikit/caikit-nlp/blob/e5127283553a4249d15c1cb78bc5b226697ae3bf/tests/modules/text_generation/test_peft_prompt_tuning.py#L81-L84

I added a test for `generate_text_func` that generates text and then tries serializing the result. I'm also parametrizing over two different model types, which is probably not really required.

**Comment by Ssukriti** [comment]
Great. Thank you! PR looks good to me

**Review by evaline-ju — APPROVED** [review]
LGTM - thanks for adding the test!

**Pull request merged**
