### PR TITLE
proposal: use setuptools/setuptools_scm for building

### PR DESCRIPTION
**Pull request by dtrifiro**
This PR changes the build system from `flit` to `setuptools`+[`setuptools_scm`](https://github.com/pypa/setuptools_scm/). The main driver behind this PR is to simplify development by having `setuptools_scm` automatically set the module version at build/install time instead of having a fixed `0.0.1` version replaced by CI.

Another advantage of using `setuptools_scm` is to have proper versions reported when using editable installs, avoiding version requirements warnings/errors.

This also adds the possibility of using `caikit_nlp.__version__`  (or `__version_tuple__`) to check  the module version at runtime

### CODE REVIEW

**Comment by dtrifiro** [comment]
An example of what the version generated by `setuptools-scm`: `0.2.2.dev39+g8cfe9b8`:  it includes git tag, number of commits since last tag and the git ref for the build.

**Comment by dtrifiro** [comment]
Hey @gabe-l-hart, do you have any bandwidth to have a look at this and/or discuss it?

**Review by gkumbhat — COMMENTED** [review]
I like this change. @gabe-l-hart or @evaline-ju or @joerunde thoughts on this? Also do we want to include this for `caikit` as well?

Currently `caikit-nlp` cannot be published to pypi itself because of peft version, but something seems this would be useful for caikit and once we are able to push caikit-nlp to pypi.

**Review by joerunde — APPROVED** [review]
@dtrifiro yeah this looks better than what we whipped up when we pulled this all out into github. Thanks!

Can you go ahead and make the change to caikit as well?

**Comment by joerunde** [comment]
Ah, I am not a code owner here so I'd actually need @gkumbhat to hit approve on this PR

**Review by gabe-l-hart — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
